### ISSUE TITLE
Required versions to run the project?

### ISSUE THREAD

**Issue by dimonoid** [netzlab/SACMES#2]
Which versions of Python and what versions of libraries (scipy, lmfit, matplotlib, numpy, etc) were tested to work fine?

I keep getting random errors, seemingly because of incompatibility with latest versions.

**Comment by vclark19** [comment]
Hello, apologies for the delay, we recommend using Python 3.8.3 (07-2020 release) to avoid incompatibility issues. We are currently updating the code for the latest Python release and should have an update by the end of this year.
